### ISSUE TITLE
Nested, Sortable Field Type

### ISSUE THREAD

**Issue by Zoramite** [grow/selective-edit#5]
Add a new field type that allows for nesting `Fields`.

Example of a simple sortable list of text fields:

```
{
  "type": "sortable",
  "key": "list_values",
  "label": "Strings",
  "fields" [
    {
      "type": "text"
    }
}
```

Example of a more complex sortable list of fields:

```
{
  "type": "sortable",
  "key": "sections",
  "label": "Sections",
  "fields" [
    {
      "type": "text",
      "key": "title",
      "label": "Title"
    },
    {
      "type": "text",
      "key": "subtitle",
      "label": "Sub Title"
    },
  ]
}
```

**Comment by jeremydw** [comment]
We probably want this to work with arbitrary levels of nesting. :) So a
list could embed other lists. Contentful does this by opening a new
tile/lightbox for every sub-list.

**Comment by Zoramite** [comment]
It already is setup to work with arbitrary levels, its mostly about how we style it.
